# Generated by Django 4.0 on 2022-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pe', 'pendiente'), ('pr', 'en proceso'), ('t', 'terminada')], default='pe', max_length=100)),
            ],
        ),
    ]
