version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code/
    env_file: ./example.env
    restart: "always"
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db:db
  db:
    restart: always
    image: postgres:latest
    env_file: ./example.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - local_postgres_data:/var/lib/postgresql/data

  nginx:
    restart: always
    build:
      dockerfile: ./nginx/Dockerfile
    env_file: example.env
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  local_postgres_data: {}
