services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py migrate && 
             python manage.py runserver
    expose:
      - 8000
    restart: "always"
    depends_on:
      - db
    links:
      - db:db