version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: "always"