version: "3.3"

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    command: ['gunicorn', 'config.wsgi:application', '--reload']

  db:
    extends:
      file: docker-compose.yml
      service: db

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

volumes:
  local_postgres_data:
  static_files: