# Generated by Django 4.0.2 on 2022-04-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('pe', 'pendiente'), ('pr', 'en proceso'), ('t', 'terminada')], default='pe', max_length=100),
        ),
    ]
