apiVersion: v1
kind: Service
metadata:
  name: tts-nginx-service
spec:
  selector:
    app: tick-tick-school
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080