apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-nginx-deployment
  labels:
    app: tick-tick-school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: armandobarragan/tick-tick-school-nginx:v1.0.0
          name: nginx
          envFrom:
            - configMapRef:
                name: tts-nginx-configmap
