apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-web-deployment
  labels:
    app: tick-tick-school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: armandobarragan/tick-tick-school-web:v1.0.0
          name: app
          command: ["./entrypoint.sh"]
          envFrom:
          - secretRef:
              name: tick-tick-school-secret
          - configMapRef:
              name: tts-web-configmap
          ports:
            - containerPort: 8000
              name: gunicorn
